### ISSUE TITLE
a question about fault detection

### ISSUE THREAD

**Issue by 943fansi** [xaleritsme/Supervised-machine-learning-methods-for-condition-monitoring-and-fault-detection-of-wind-turbines#1]
Thanks for sharing. It seems like you are using a regression model to predict variable values. I wonder how this ties into failure detection. Are there other things waiting for an update?

**Comment by aleksander-piprek** [comment]
Hi. I guess this late response won't mean much as it is 1.5 year later but I will answer the question.

The procedure was as follows: 
1. I took the data from La Haute Borne of wind turbines with various information including generator temperature and gearbox temperature.
2. Pre-processed the data so that we are dealing with the data that's representing correct working of the turbine. 
3. Train these regression models using pre-processed data.
4. During testing part, we check whether models are working as intented.
5. During the experiment part I had to find parts of the data where the temperature rises or other failure, then used the model on data from few days ago to see whether the models predicts the actual failure.

I hope this clears up a bit :)

**Comment by 943fansi** [comment]
> Hi. I guess this late response won't mean much as it is 1.5 year later but I will answer the question.
> 
> The procedure was as follows:
> 
> 1. I took the data from La Haute Borne of wind turbines with various information including generator temperature and gearbox temperature.
> 2. Pre-processed the data so that we are dealing with the data that's representing correct working of the turbine.
> 3. Train these regression models using pre-processed data.
> 4. During testing part, we check whether models are working as intented.
> 5. During the experiment part I had to find parts of the data where the temperature rises or other failure, then used the model on data from few days ago to see whether the models predicts the actual failure.
> 
> I hope this clears up a bit :)

Thanks for the update on the issue.
